pref: unescape reqURI.
webp-sh/webp_server_go pull request #57
Opened 2020-11-22 13:39 UTC by ruibaby

如果图片的实际访问路径中包含一些特殊的字符（如空格或中文）被 encodeURL 之后，直接 `c.Path()` 取到的文件路径和真实的文件路径是不一致的，所以会抛出 `image not found` 的异常。

2020-11-22 14:25 UTC, BennyThink commented
感谢提出这个问题，仔细想了一下，确实会有这种可能。
但是我这样修改个人是不推荐的，改了一些函数的签名，这样会导致维护比较麻烦。

我的第一想法是使用fallback策略，在encoder中。

但是由于我们的这个场景更特殊，我觉得可以简单的用一种非常暴力的策略：无条件URL解码，这样总是会找到文件系统中的文件的。然后只需要加一个测试用例就可以了。

@n0vad3v 你觉得这个想法怎么样 技术上应该是可行的

2020-11-22 14:25 UTC, BennyThink requested changes
see comments

2020-11-23 02:00 UTC, ruibaby commented
@BennyThink 你们可以讨论解决一下这个问题哦，我对 go 不是太熟悉，这个 pr 就当做我提的一个 issue 吧。😁

2020-11-24 10:27 UTC, BennyThink commented
> @BennyThink 你们可以讨论解决一下这个问题哦，我对 go 不是太熟悉，这个 pr 就当做我提的一个 issue 吧。😁

https://github.com/webp-sh/webp_server_go/pull/58
参考实现

2020-11-25 02:39 UTC, closed without merging